export const blogPosts = [
  {
    id: 1,
    title: "Melestarikan Kue Tradisional Indonesia di Era Modern",
    slug: "melestarikan-kue-tradisional-indonesia",
    excerpt:
      "Bagaimana kita dapat melestarikan kekayaan kuliner tradisional Indonesia di tengah gempuran makanan modern? Artikel ini membahas pentingnya inovasi dalam menjaga warisan kuliner nusantara.",
    content: "",
    image: "/placeholder.svg?height=600&width=1200",
    category: "Kuliner Nusantara",
    date: "12 Juni 2023",
    author: {
      name: "Dewi Suryani",
      avatar: "/placeholder.svg?height=100&width=100",
      bio: "Seorang pecinta kuliner Indonesia yang berdedikasi untuk melestarikan dan memperkenalkan kekayaan kuliner Nusantara kepada masyarakat luas.",
    },
    tags: ["kue tradisional", "kuliner", "warisan", "indonesia"],
    likes: 45,
    comments: 12,
    readTime: "7 menit membaca",
  },
  {
    id: 2,
    title: "Resep Bolu Pandan Keju yang Lembut dan Wangi",
    slug: "resep-bolu-pandan-keju",
    excerpt:
      "Bolu pandan keju adalah salah satu varian bolu yang sangat populer di Indonesia. Paduan rasa pandan yang wangi dengan keju yang gurih membuat kue ini memiliki cita rasa yang khas.",
    content: "",
    image: "/placeholder.svg?height=600&width=1200",
    category: "Resep",
    date: "5 Juni 2023",
    author: {
      name: "Chef Rina",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    tags: ["resep", "bolu", "pandan", "keju"],
    likes: 78,
    comments: 23,
    readTime: "5 menit membaca",
  },
  {
    id: 3,
    title: "Tips Membuat Dessert Box yang Instagramable",
    slug: "tips-dessert-box-instagramable",
    excerpt:
      "Dessert box tidak hanya harus enak, tapi juga harus cantik untuk dipotret. Simak tips dan trik membuat dessert box yang tidak hanya lezat tapi juga menarik secara visual.",
    content: "",
    image: "/placeholder.svg?height=600&width=1200",
    category: "Tips & Trik",
    date: "28 Mei 2023",
    author: {
      name: "Anisa Putri",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    tags: ["dessert box", "tips", "fotografi", "instagram"],
    likes: 120,
    comments: 34,
    readTime: "6 menit membaca",
  },
  {
    id: 4,
    title: "Mengenal Berbagai Jenis Tepung untuk Membuat Kue",
    slug: "mengenal-jenis-tepung-kue",
    excerpt:
      "Tepung adalah bahan dasar dalam pembuatan kue. Mengenal berbagai jenis tepung dan fungsinya akan membantu Anda membuat kue dengan tekstur yang sempurna.",
    content: "",
    image: "/placeholder.svg?height=600&width=1200",
    category: "Tips & Trik",
    date: "20 Mei 2023",
    author: {
      name: "Chef Rina",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    tags: ["tepung", "baking", "tips", "kue"],
    likes: 65,
    comments: 18,
    readTime: "8 menit membaca",
  },
  {
    id: 5,
    title: "Event: Workshop Pembuatan Kue Tradisional Bersama Chef Terkenal",
    slug: "workshop-kue-tradisional",
    excerpt:
      "Rasa Nusantara mengadakan workshop pembuatan kue tradisional yang akan dibawakan oleh chef terkenal. Jangan lewatkan kesempatan belajar langsung dari ahlinya!",
    content: "",
    image: "/placeholder.svg?height=600&width=1200",
    category: "Event",
    date: "15 Mei 2023",
    author: {
      name: "Tim Rasa Nusantara",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    tags: ["workshop", "event", "kue tradisional", "chef"],
    likes: 32,
    comments: 8,
    readTime: "4 menit membaca",
  },
  {
    id: 6,
    title: "Sejarah dan Filosofi di Balik Kue Keranjang",
    slug: "sejarah-filosofi-kue-keranjang",
    excerpt:
      "Kue keranjang atau nian gao memiliki sejarah panjang dan filosofi mendalam dalam budaya Tionghoa. Mari mengenal lebih dalam tentang kue yang sering disajikan saat perayaan Imlek ini.",
    content: "",
    image: "/placeholder.svg?height=600&width=1200",
    category: "Kuliner Nusantara",
    date: "10 Mei 2023",
    author: {
      name: "Dewi Suryani",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    tags: ["kue keranjang", "imlek", "budaya", "sejarah"],
    likes: 54,
    comments: 15,
    readTime: "9 menit membaca",
  },
  {
    id: 7,
    title: "Cara Menyimpan Kue Agar Tetap Segar dan Tahan Lama",
    slug: "cara-menyimpan-kue",
    excerpt:
      "Menyimpan kue dengan benar akan mempertahankan kesegaran dan memperpanjang umur simpannya. Simak tips dan trik menyimpan berbagai jenis kue agar tetap enak saat disantap.",
    content: "",
    image: "/placeholder.svg?height=600&width=1200",
    category: "Tips & Trik",
    date: "5 Mei 2023",
    author: {
      name: "Anisa Putri",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    tags: ["penyimpanan", "kue", "tips", "kesegaran"],
    likes: 89,
    comments: 27,
    readTime: "5 menit membaca",
  },
]

export type BlogPost = (typeof blogPosts)[0]
