export const products = [
  // Previous products (1-20)...

  {
    id: 21,
    name: "Kue Lumpur",
    description: "Kue lumpur dengan kentang pilihan dan topping kismis",
    longDescription:
      "Kue lumpur tradisional dengan tekstur lembut dari kentang pilihan, disajikan dengan topping kismis premium.",
    price: 55000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "kue-basah",
    subCategory: "jajanan-pasar",
    isNew: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 85,
    stock: 25,
    minimumOrder: 1,
    weight: "500 gram",
    size: "10 pcs",
    preOrderDays: 1,
  },
  {
    id: 22,
    name: "Onde-onde",
    description: "Onde-onde dengan isian kacang hijau dan taburan wijen",
    longDescription: "Onde-onde dengan kulit kenyal, isian kacang hijau yang lembut, dan balutan wijen yang renyah.",
    price: 45000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "kue-basah",
    subCategory: "jajanan-pasar",
    isNew: false,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 65,
    stock: 30,
    minimumOrder: 1,
    weight: "400 gram",
    size: "10 pcs",
    preOrderDays: 1,
  },
  {
    id: 23,
    name: "Kue Cucur",
    description: "Kue cucur gula merah tradisional",
    longDescription: "Kue cucur tradisional dengan gula merah asli, tekstur berserat dan rasa manis yang pas.",
    price: 40000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "kue-basah",
    subCategory: "jajanan-pasar",
    isNew: true,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 45,
    stock: 20,
    minimumOrder: 1,
    weight: "400 gram",
    size: "10 pcs",
    preOrderDays: 1,
  },
  {
    id: 24,
    name: "Donat Kentang",
    description: "Donat kentang premium dengan berbagai topping",
    longDescription:
      "Donat kentang yang lembut dengan berbagai pilihan topping premium seperti coklat, matcha, dan karamel.",
    price: 75000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "kue-modern",
    subCategory: "donat",
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 120,
    stock: 40,
    minimumOrder: 1,
    weight: "600 gram",
    size: "6 pcs",
    preOrderDays: 1,
  },
  {
    id: 25,
    name: "Pie Buah",
    description: "Pie dengan topping buah segar pilihan",
    longDescription: "Pie dengan kulit renyah, filling custard lembut, dan topping buah segar musiman.",
    price: 150000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "kue-modern",
    subCategory: "pie",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 95,
    stock: 15,
    minimumOrder: 1,
    weight: "800 gram",
    size: "22 cm",
    preOrderDays: 2,
  },
  {
    id: 26,
    name: "Croissant",
    description: "Croissant butter premium dengan lapisan sempurna",
    longDescription: "Croissant dengan lapisan butter premium yang berlapis-lapis, renyah di luar dan lembut di dalam.",
    price: 125000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "kue-modern",
    subCategory: "pastry",
    isNew: true,
    isBestSeller: false,
    rating: 4.7,
    reviewCount: 60,
    stock: 20,
    minimumOrder: 1,
    weight: "500 gram",
    size: "6 pcs",
    preOrderDays: 2,
  },
  {
    id: 27,
    name: "Mochi Ice Cream",
    description: "Mochi dengan filling ice cream premium",
    longDescription: "Mochi dengan kulit lembut dan filling ice cream premium dalam berbagai varian rasa.",
    price: 120000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "dessert-modern",
    subCategory: "mochi",
    isNew: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 75,
    stock: 30,
    minimumOrder: 1,
    weight: "600 gram",
    size: "8 pcs",
    preOrderDays: 1,
  },
  {
    id: 28,
    name: "Cheese Tart",
    description: "Cheese tart dengan cream cheese premium",
    longDescription: "Cheese tart dengan kulit renyah dan filling cream cheese premium yang creamy.",
    price: 180000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "kue-modern",
    subCategory: "tart",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 88,
    stock: 25,
    minimumOrder: 1,
    weight: "600 gram",
    size: "6 pcs",
    preOrderDays: 2,
  },
  {
    id: 29,
    name: "Tiramisu Cake",
    description: "Tiramisu cake dengan coffee premium",
    longDescription: "Tiramisu cake dengan lapisan mascarpone cheese dan coffee premium import.",
    price: 350000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "cake",
    subCategory: "specialty-cake",
    isNew: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 150,
    stock: 10,
    minimumOrder: 1,
    weight: "1000 gram",
    size: "20x20 cm",
    preOrderDays: 2,
  },
  {
    id: 30,
    name: "Fruit Cake Premium",
    description: "Fruit cake dengan dried fruits dan nuts premium",
    longDescription: "Fruit cake premium dengan campuran dried fruits dan nuts pilihan, perfect untuk hadiah.",
    price: 400000,
    images: ["/placeholder.svg?height=600&width=600"],
    category: "cake",
    subCategory: "specialty-cake",
    isNew: true,
    isBestSeller: false,
    rating: 4.8,
    reviewCount: 65,
    stock: 15,
    minimumOrder: 1,
    weight: "1200 gram",
    size: "20x20 cm",
    preOrderDays: 3,
  },
]

export const categories = [
  {
    id: "all",
    name: "Semua Produk",
    description: "Semua produk kami",
  },
  {
    id: "kue-kering",
    name: "Kue Kering",
    description: "Aneka kue kering premium",
    subCategories: [
      { id: "nastar", name: "Nastar" },
      { id: "kastengel", name: "Kastengel" },
      { id: "putri-salju", name: "Putri Salju" },
      { id: "sagu", name: "Sagu Keju" },
      { id: "lidah-kucing", name: "Lidah Kucing" },
      { id: "cookies", name: "Cookies" },
    ],
  },
  {
    id: "kue-basah",
    name: "Kue Basah",
    description: "Aneka kue basah tradisional",
    subCategories: [
      { id: "jajanan-pasar", name: "Jajanan Pasar" },
      { id: "sus", name: "Kue Sus" },
    ],
  },
  {
    id: "kue-tradisional",
    name: "Kue Tradisional",
    description: "Kue tradisional Indonesia",
    subCategories: [
      { id: "lapis-legit", name: "Lapis Legit" },
      { id: "lapis-surabaya", name: "Lapis Surabaya" },
      { id: "jajanan-pasar", name: "Jajanan Pasar" },
    ],
  },
  {
    id: "kue-modern",
    name: "Kue Modern",
    description: "Aneka kue modern",
    subCategories: [
      { id: "donat", name: "Donat" },
      { id: "pie", name: "Pie" },
      { id: "pastry", name: "Pastry" },
      { id: "tart", name: "Tart" },
    ],
  },
  {
    id: "cake",
    name: "Cake",
    description: "Aneka cake premium",
    subCategories: [
      { id: "birthday-cake", name: "Birthday Cake" },
      { id: "specialty-cake", name: "Specialty Cake" },
    ],
  },
  {
    id: "dessert-modern",
    name: "Dessert Modern",
    description: "Aneka dessert modern",
    subCategories: [
      { id: "dessert-box", name: "Dessert Box" },
      { id: "mochi", name: "Mochi" },
    ],
  },
  {
    id: "hampers",
    name: "Hampers",
    description: "Hampers untuk berbagai acara",
    subCategories: [
      { id: "regular-hampers", name: "Regular Hampers" },
      { id: "premium-hampers", name: "Premium Hampers" },
      { id: "corporate-hampers", name: "Corporate Hampers" },
    ],
  },
]

export type Product = (typeof products)[0]
export type Category = (typeof categories)[0]
